// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for tailwind-selfheal.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const tailwindSelfhealBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/tailwind-selfheal.bridge.ts
  (function() {
    var CHECK_DELAY_MS = 700;
    var RETRY_DELAY_MS = 1200;
    var MAX_ATTEMPTS = 3;
    function tailwindProducedOutput() {
      var probe = document.createElement("div");
      probe.className = "hidden";
      probe.style.position = "absolute";
      probe.style.top = "-9999px";
      probe.style.left = "-9999px";
      probe.setAttribute("aria-hidden", "true");
      document.documentElement.appendChild(probe);
      var applied = false;
      try {
        applied = window.getComputedStyle(probe).display === "none";
      } catch (_err) {
      }
      try {
        probe.remove();
      } catch (_err) {
      }
      return applied;
    }
    function reloadTailwindScripts() {
      var scripts = document.querySelectorAll(
        'script[src*="tailwindcss/browser"]'
      );
      if (scripts.length === 0) return false;
      for (var i = 0; i < scripts.length; i++) {
        var src = scripts[i].getAttribute("src");
        if (!src) continue;
        var fresh = document.createElement("script");
        fresh.src = src;
        document.head.appendChild(fresh);
      }
      return true;
    }
    function scheduleCheck(attempt) {
      setTimeout(
        function() {
          if (tailwindProducedOutput()) return;
          var hasTailwindScript = !!document.querySelector(
            'script[src*="tailwindcss/browser"]'
          );
          if (!hasTailwindScript) return;
          if (attempt >= MAX_ATTEMPTS) return;
          if (reloadTailwindScripts()) scheduleCheck(attempt + 1);
        },
        attempt === 0 ? CHECK_DELAY_MS : RETRY_DELAY_MS
      );
    }
    function start() {
      scheduleCheck(0);
    }
    if (document.readyState === "complete") {
      start();
    } else {
      window.addEventListener("load", start);
    }
  })();
})();
`;
