// Re-export everything from the shared app config package
export {
  type AppDefinition,
  type AppConfig,
  APP_REGISTRY,
  DEFAULT_APPS,
  TEMPLATE_APPS,
  FRAME_PORT,
  getAppUrl,
  getTemplateGatewayAppUrl,
  getTemplateGatewayUrl,
  getAppById,
  toAppDefinition,
  generateAppId,
  templateToAppConfig,
  type FrameSettings,
  TEMPLATES,
  visibleTemplates,
  getTemplate,
  type TemplateMeta,
} from "@agent-native/shared-app-config";
